# Header
menu:
  首页: /
  归档: /archives

rss: /atom.xml
nav: right
mobile_nav: right



# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- userinfo
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tagcloud
- archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Background
background_image: /images/bg.jpeg
background_title: 图片来自网络

#Userinfo
author: 陌生百路
slogan: 淡漠人生十数载 留意精彩一瞬间
avatar: /images/code.png
avatar_title: 图片来自网络

# Article code panel: cloud doorframe mac
highlightPanel: cloud

#Gitment

# Miscellaneous
google_analytics:
gauges_analytics:
google_site_verification: 
baidu_site_verification: 
favicon: /images/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
keywords:

